# Generated by Django 5.0.13 on 2025-11-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agencia_de_viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='id_destino',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
