# Generated by Django 5.0.13 on 2025-12-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agencia_de_viajes', '0002_alter_destino_id_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='id_alojamiento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
