# Generated by Django 5.0.13 on 2025-12-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agencia_de_viajes', '0003_alter_alojamiento_id_alojamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente_viajes',
            name='id_agente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente_viajes',
            name='id_cliente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paquete_turistico',
            name='id_paquete',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva_viaje',
            name='id_reserva',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='id_vuelo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
